### ISSUE TITLE
발표자료 1, 2, 3 비교 분석 정리

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#1]
[due to : 2021-05-20 오후 11:00]

녹화본과 발표자료 등을 토대로, 타 조(4개)를 포함하여 자료를 정리합니다.
(주로 저희 팀과의 차이를와 부족함을 비교하며 정리해주시면 감사하겠습니다.)

토론 1, 2, 3에서 가장 높은 점수를 받은 4개 팀(이하 A, B, C, D)을 포함합니다.
토론 1, 2에 대한 녹화본이 필요하신 분들은 코멘트 남겨주세요.

(팀을 선택하고 댓글로 선택한 팀을 적어 주시거나, 아래의 체크리스트를 활용)

~~ - [ ] A (토론1 - 3조, 토론 2 - 6조) ~~
- [ ] B (토론 1 - 1조, 토론 2 - 3조)
~~ - [ ] C (토론 1 - 2조, 토론 2 - 4조) ~~ 
~~ - [x] D (토론 1 - 6조, 토론 2 - 5조) ~~

~~(토론 3 발표는 아직 나오지 않았으나, A, B는 6조 C, D는 3조를 해주시면 됩니다.)~~

오해의 소지가 있어 위 문구를 삭제합니다.

**Comment by ChoiJunhee** [comment]
A는 제가 맡겠습니다.

**Comment by ChoiJunhee** [comment]
@HwangTr @zhanghuiyan99 @kang961105  금일 내로 업로드 부탁드립니다... 그래야 취합해서 정리할 수 있어요 

다른 조에 비해 부족했다고 생각한 점이나, 다른 조가 잘했다 싶은 부분을 간단히 올려주시면 됩니다.

**Comment by zhanghuiyan99** [comment]
토론2-6조의  조리가 정확합니다.
토론1-3조 해명 데이터가 분명합니다.

**Comment by ChoiJunhee** [comment]
> 토론2-6조의 조리가 정확합니다.
> 토론1-3조 해명 데이터가 분명합니다.

@zhanghuiyan99 Please submit a brief report with the relevant details attached.

**Comment by zhanghuiyan99** [comment]
[D (토론 1 - 6조, 토론 2 - 5조).pdf](https://github.com/ChoiJunhee/INE5015_bigdata_analytics/files/6515949/D.1.-.6.2.-.5.pdf)

**Comment by ChoiJunhee** [comment]
> [D (토론 1 - 6조, 토론 2 - 5조).pdf](https://github.com/ChoiJunhee/INE5015_bigdata_analytics/files/6515949/D.1.-.6.2.-.5.pdf)

Using git (using a tool such as gitkraken), upload the file to [아래 링크]. (If it is difficult, i will upload it in later.)

https://github.com/ChoiJunhee/INE5015_bigdata_analytics/tree/main/PPT_files

**Comment by ChoiJunhee** [comment]
죄송합니다. 동영상 폴더 정리하다 실수로 토론 1, 2영상을 삭제했습니다. 
레포트는 절반정도 완성되어 있어 다른 분이 하시거나, 제가 기회가 되면 다시 하는 것으로 하겠습니다.

이에 금일 내로 토론 3의 상위 4팀에 대한 레포트로 대체하여 업로드 하겠습니다.

**Comment by ChoiJunhee** [comment]
> 죄송합니다. 동영상 폴더 정리하다 실수로 토론 1, 2영상을 삭제했습니다.
> 레포트는 절반정도 완성되어 있어 다른 분이 하시거나, 제가 기회가 되면 다시 하는 것으로 하겠습니다.
> 
> 이에 금일 내로 토론 3의 상위 4팀에 대한 레포트로 대체하여 업로드 하겠습니다.

어제 업로드에 이어 오늘은 저희 발표 자료의 부족한 부분에 대해서 레포트 하겠습니다. 
주말 풀타임, 평일 하프타임 알바를 하고 있어 약간 일정이 미뤄질 수 있는 점은 양해 부탁드립니다.

**Comment by ChoiJunhee** [comment]
제출 기한을 다시 정정했습니다. 참여 부탁드립니다.

**Comment by ChoiJunhee** [comment]
기한 만료로 중단합니다.
