### ISSUE TITLE
데이터 시각화 요청용 이슈

### ISSUE THREAD

**Issue by HwangTr** [ChoiJunhee/INE5015_bigdata_analytics#12]
현재 제가 표준편차 0 또는 0에 가까운 표준편차를 가진 열과 이상치 전처리 대한 시각화를 진행 중입니다. 

데이터 전처리 전 후의 모습에 대하여 현재 진행하려는 방식이 표준편차는 마커 형태, 즉 점 도표 형식으로 각 feature의 표준편차 분포를 보여주고 이후 전처리된 형태로 보여주려고 합니다.

또한 이상치에 대해선 heatmap 형태를 이용할려고 합니다. 

혹시 다른 방법으로의 시각화 방식이 생각나신다면 알려주시면 감사하겠습니다. 

또 제가 하는 방식에서 개선점이 있다면 그 부분에 대해서도 알려주시면 감사하겠습니다. 

heatmap에 대해서는 저희가 가진 feature의 개수 , 즉 열의 개수가 많아 시각적으로 보았을 때 이상치 부분이 뚜렷하게 나오지 않고 있어 이 부분에 대해서도 괜찮은 생각이 있다면 알려주시면 감사하겠습니다.

**Comment by ChoiJunhee** [comment]
@HwangTr 줄바꿈이 안되어 있어 내용 수정했습니다.

1. 데이터 전 처리 전 후의 모습이라 하면 여러가지 내용이 있을 수 있는데, 점 도표가 무엇인지 검색해봐도 잘 와닿지 않습니다. 

제가 이해한 바로는  https://support.minitab.com/ko-kr/minitab/18/distribution_plot_hypothetical_standard_normal_distribution.png 와 같은 그래프인데 점 (각 Feature) 으로 구성되어 있다는 것이겠죠??

여기서 점들의 색상 변화가 추가된다면 좋을 것 같습니다.

2. heatmap 은 3차 발표 때 타 조가 썼는데 보기 좋긴 하더라구요. 메인은 그렇게 진행해 주시고 결과물을 보고 보완해야 할 점을 말씀드리겠습니다.

3. 이상치가 제거된 상태에서 만드신건지 heatmap에 대한건 코드와 결과물을 좀 봐야 할 것 같네요.

**Comment by HwangTr** [comment]
1. 해당 부분은 각 feature별 표준편차를 점이 아닌 선으로 x축이 각 feature y축이 표준편차로 해서 나타냈습니다
2. 해당 부분에 대해서 확인하고 진행해보겠습니다
3. 현재 ipynb 파일을 갖고 진행하고 있어 다시 python 파일을 보면서 조정해 나가겠습니다.

**Comment by HwangTr** [comment]
![heat](https://user-images.githubusercontent.com/32156431/119256032-98d0be80-bbf9-11eb-85f8-5ffdcb4e87f4.PNG)
![3heat](https://user-images.githubusercontent.com/32156431/119256035-9d957280-bbf9-11eb-9631-da36efa516da.PNG)

2번 부분에 대해서 아마 3조의 히트맵을 말씀하신 것 같습니다. 
위의 사진이 제가 만든 아주 간단한 heatmap입니다. 아래의 사진은 3조의 발표에서의 heatmap이고 seaborn, missingno 중 어떤걸 이용하냐 차이입니다.

**Comment by ChoiJunhee** [comment]
> 1. 해당 부분은 각 feature별 표준편차를 점이 아닌 선으로 x축이 각 feature y축이 표준편차로 해서 나타냈습니다
> 2. 해당 부분에 대해서 확인하고 진행해보겠습니다
> 3. 현재 ipynb 파일을 갖고 진행하고 있어 다시 python 파일을 보면서 조정해 나가겠습니다.

1. x축을 표준편차, y축을 feature로 해야 될 것 같습니다. 특정 편차 이내 / 이외의 점에는 색상을 달리 하는 방법으로 가시성을 높이면 될듯 합니다.


2. 파일을 바꾸어 진행해 보셔야 할 것 같습니다. 지금 진행중인 파이썬 파일에서는 Refine 4 Step에서 처리 방법에 따라 280~340여개의 피쳐가 있습니다. 최종 Refine Step에서는 170~230 정도의 피쳐를 예상합니다.


3. 파이썬이나 주피터나 별 차이 없습니다. 실행 주체의 차이라고 봅니다. + 뭐가 되었든 직관적 + 가시성이 좋으면 좋겠습니다.

**Comment by zhanghuiyan99** [comment]
https://towardsdatascience.com/complete-guide-to-data-visualization-with-python-2dd74df12b5e

https://pandas.pydata.org/pandas-docs/stable/user_guide/visualization.htm

[algorithms for data visualization.pdf](https://github.com/ChoiJunhee/INE5015_bigdata_analytics/files/6539425/algorithms.for.data.visualization.pdf)

**Comment by ChoiJunhee** [comment]
이번 0526 폴더에 상세히 나뉜 데이터셋들이 있습니다.

이것들을 가지고 피쳐들의 특징을 나타낼 수 있는 시각화 데이터를 요청합니다.

특히 exclusive 한 파일을 우선하여 올려주셨으면 합니다. (따로따로 올려주셔도 좋습니다)

**Comment by ChoiJunhee** [comment]
> 이번 0526 폴더에 상세히 나뉜 데이터셋들이 있습니다.
> 
> 이것들을 가지고 피쳐들의 특징을 나타낼 수 있는 시각화 데이터를 요청합니다.
> 
> 특히 exclusive 한 파일을 우선하여 올려주셨으면 합니다. (따로따로 올려주셔도 좋습니다)
> 
> 커밋넘버
> [6cc7d6f](https://github.com/ChoiJunhee/INE5015_bigdata_analytics/commit/6cc7d6f145db60c79772918f84ef9ce15555c2ba)

**_You only need to work on files with rf3 prefix._**
