### ISSUE TITLE
프로젝트 진행 방식 변경안

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#13]
1. 데이터 전처리, 데이터 모델링, 데이터 튜닝등 시스템 자원이나 프로그래밍이 필요한 부분은 대부분 제가 맡겠습니다. 

2. @HwangTr 님은 데이터 시각화에 주력하여 남은 프로젝트를 진행합니다.

3. @zhanghuiyan99 님은 데이터 전처리, 데이터 모델링, 데이터 튜닝에서 사용되는 여러 알고리즘이나 방법들을 조사하여 프로그래밍에 사용될 기능들의 정보를 정리해 주시길 바랍니다.

4. @kang961105 프로그래밍 과정에서 있는 버그, 리팩토링 등 성능 향상에 대한 피드백을 주시고, @zhanghuiyan99 님과 @HwangTr 님의 자료에 대한 피어리뷰를 부탁드립니다.

_3. @zhanghuiyan99 hopes to organize information on functions to be used in programming by investigating_
_various algorithms and methods used in data preprocessing, data modeling, and model tuning._

_4. @kang961105 Please give us feedback on performance improvements such as bugs and refactorings_
_in the programming process, and ask for peer review of @zhanghuiyan99 and @HwangTr's files._

지금 진행하고 있는 전처리->모델링 과정에서 여러 방법 들을 사용하여 다양한 시각의 데이터를 얻을 수 있도록 개발 방향을 바꾸어 진행하겠습니다.

위와 같이 변경하고자 하는데, 동의하시거나 다른 의견 있으시면 댓글 남겨주시길 바랍니다.
_I would like to change as above, but if you agree or have any other opinions, please leave a comment._

**Comment by HwangTr** [comment]
저는 동의합니다
