### ISSUE TITLE
결측치 데이터 관련 토의

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#14]
![image](https://user-images.githubusercontent.com/43108674/119282071-2a304700-bc73-11eb-8e3a-bc4768f6c9dd.png)

현재 커밋된 파일을 보시면 알다시피 결측치 데이터는 Scikit-learn에서 제공하는 Imputue 메소드를 사용하고 있습니다. 

https://scikit-learn.org/stable/modules/generated/sklearn.impute.IterativeImputer.html

위 공식 사이트 문서에 보면 하이퍼 파라미터 값을 조절할 수 있게 되어 있는데 

현재는 조절이 되어 있지 않은 상태입니다.

CUDA 연산이 지원되지 않는 관계로 Imputation 한번 할 때마다 약 10여분씩 걸리는 상황이라, 브루트 포스와 같은 방법으로는 최적의 값을 구하기 어려울 것 같습니다.

그래서 해당 Imputer의 파라미터를 조절할 적절한 자료나, 실험 결과 등을 알려주셨으면 좋겠습니다.

@zhanghuiyan99 @kang961105

**Comment by ChoiJunhee** [comment]
https://scikit-learn.org/stable/auto_examples/impute/plot_missing_values.html#sphx-glr-auto-examples-impute-plot-missing-values-py

위와 같이 공식 사이트에서 제공하는 자료도 많으니 각자 생각하는 좋은 방법들을 꼭 오늘까지 공유 부탁드립니다.

**Comment by zhanghuiyan99** [comment]
https://scikit-learn.org/stable/modules/impute.html

https://medium.com/technofunnel/handling-missing-data-in-python-using-scikit-imputer-7607c8957740

https://stackoverflow.com/questions/25239958/impute-categorical-missing-values-in-scikit-learn

https://contactsunny.medium.com/handle-missing-data-in-your-training-dataset-with-scikit-imputer-f4bbf005fc5e

맞는지는 모르겠지만 도움이 될 것 같아요.

**Comment by ChoiJunhee** [comment]
> https://scikit-learn.org/stable/modules/impute.html
> 
> https://medium.com/technofunnel/handling-missing-data-in-python-using-scikit-imputer-7607c8957740
> 
> https://stackoverflow.com/questions/25239958/impute-categorical-missing-values-in-scikit-learn
> 
> https://contactsunny.medium.com/handle-missing-data-in-your-training-dataset-with-scikit-imputer-f4bbf005fc5e
> 
> 맞는지는 모르겠지만 도움이 될 것 같아요.

감사합니다. 해당 이슈는 처리되었고 곧 커밋할 예정입니다.
