### ISSUE TITLE
csv read error

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#18]
문제 : step4에서 pass, fail이 제대로 나뉘었는지 구분을 못하겠음...

현재 절반 진행된 코드가 있는데

pass/fail이 잘 나뉘었는지, 코드에 맞는 결과물이 나왔는지, 

step4에 있는 시각화 이미지들을 보고 문제가 있는지 

코드 리뷰 한번씩 부탁드립니다.

---

_I have a code half done right now._

_Whether pass/fail is well separated, and whether the results match the code,_

_Look at the visualization images in step 4 and see if there are any problems_

**Please my code review (and visualization images) once.**

**Comment by ChoiJunhee** [comment]
추가) visualization.py에서 시각화를 진행했습니다.

**Comment by kang961105** [comment]
x축이랑 y축이 의미하는게 뭔가요?

**Comment by ChoiJunhee** [comment]
> x축이랑 y축이 의미하는게 뭔가요?

visualization은 아직 인터페이스 수준이라 무시하셔도 됩니다.
