### ISSUE TITLE
마지막 발표 정리, 향후 계획 토의 요청 

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#20]
1조 ~ 7조의 발표를 다시 시청하고,  각 조의 진행 방법, 장/단점 및 교수님의 피드백을 정리하여

이 코멘트에다 남겨주시면, 그에 대해 서로 토의하는 시간을 가졌으면 합니다.

~~_(데이터 전처리 과정에서의 선택한 알고리즘, 그에 따른 결과값, 시각화 데이터를 모두 고려해 맡은 조의 점수를 10점 만점으로 평가해 주시면, 조장님이 메일 발송 하는 것으로 했으면 좋겠습니다.)_~~
**카카오톡으로 투표 공지했습니다. 모두 확인해주세요.**

토의의 주 내용은 다음 3가지 입니다.
1. 이번 발표로 인해 우리가 부족한 부분은 무엇이고, 어떻게 진행해야 하는지.
2. 각 조의 장단점을 보며 우리가 벤치마킹할 수 있는 부분은 있는지.
3. 협업에 있어 부족한 부분이나 미숙했던 부분을 개선. 시험 일정과 같은 일정을 공유하는 등등..

기한 : 2021-06-03 (목) 오후 6:00

@ChoiJunhee 4조, 5조
@HwangTr 1조 7조
@kang961105 3조

---
### English

_watch the presentations of group 6, 7 again, and summarize each group's progress method, advantages, disadvantages, and professor's feedback._

_you must leave it in this comment. we can take the time to discuss it with each other._

_and... please evaluate the algorithm in the pre-processing process, results and visualization data, improvement contests, etc...._

_the main contents of the discussion is the following three._

_1. what are the shortcomings of this announcement and how should we preoceed?_

_2. looking at the pros and cons of each group, is there anything we can benchmarking?_

_3. Is there a better way to collaborate, and I would like you to share your own test schedule._

_**DEADLINE : 2021-06-03 (THU) 18:00**_

@zhanghuiyan99  2조, 6조

---

7b2d0f1727cfefa62aa505ac861942641ef01ede 커밋 내용도 한번 읽어주시면 감사하겠습니다. 

---

**Comment by ChoiJunhee** [comment]
#### 시험 일정 공유
06월 03일 13:30 ~ 14:00 - 산업인공지능전공면접

06월 06일 11:20 ~ 11:50 - 기업비즈니스싸강 기말고사

06월 08일 09:00 ~ 14:00 - 건보공단 제출용 Full-battery 검사
06월 09일 09:00 ~ 11:00 - 컴퓨터네트워크 기말고사
06월 09일 15:00 ~ 17:00 - 시스템프로그래밍 기말고사

06월 15일 (시간 미정) 멀티미디어정보처리 기말고사

06월 17일 18:00 ~ 20:00 - 운영체제 기말고사

**Comment by zhanghuiyan99** [comment]
2조-8
훈련 셋과 검증 셋 모두 오버 샘플링.
샘플링과 비샘플링 데이터의 비교가 있습니다.
모델의 부족점을 분석합니다.


6조-9
（이 그룹의 발표, 나는 완전한 파워포인트를 볼 수 없습니다
중간에 몇 페이지가 새었는데 잘리지 않았어요.）
기존 Feature Selection 결과를 보여줬습니다.
Permutation Feature Importance와 같은 다른 방법과 비교.

**Comment by zhanghuiyan99** [comment]
6월 14일 13:30-14:30 IoT이해와활용
6월 15일 9:00-10:30 이산수학
6월 17일 13:00~14:00 계량경영
6월 18일 (시간 미정) 전략경영론
남은 수업은 잠시 날짜 미정입니다
