### ISSUE TITLE
0.1.6 update 관련 질문

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#25]
[최준희] [오전 10:49] 오늘 오후 내로 Feature Selection까지 구현한 버전 올리도록 하겠습니다. 내일~내일모레는 병원 방문이랑 시험이 있어 아마 안산 내려가서 머물 예정이라 업데이트가 어렵습니다...

[최준희] [오후 1:47] 방금 0.1.6 커밋 올렸습니다. 주 된 내용은 Feature Selection 이전 자잘한 버그 수정 및 스케일링 알고리즘 선정, 그리고 오타로 인해 데이터 셋을 전부 다시 계산했습니다. 

이전에 올렸던 버전에서 특정한 수치를 선정한 근거가 되는 이미지 데이터는 0.2 Major 이전에 업로드 하고, 질문하고 싶은 내용이 하나 있는데

[최준희] [오후 1:48] 스케일 과정에서 Normalize를 추가 사용해야 하는건지, 아니면 지금처럼 MinMax와 Standardzation 을 사용해야 하는건지 잘 모르겠는데 제 생각에는 각 피쳐간 독립적이고 각 데이터는 1차원이라 생각해서 필요 없어 보여 제거했습니다.

[최준희] [오후 1:49] 마지막으로 MinMax 스케일링을 거친 데이터들 중 0 아니면 1에 매우 가깝거나 그냥 0, 1인 데이터들이 있는데 결측치 처리 하듯이 일정 비율 이상 가진 피쳐는 제거할 계획인데 다른 의견 있으면 어느 경로로든 알려주시길 바랍니다.

카톡에 올렸던 내용 그대로 가져왔습니다. 

질문 1. Normalize 스케일링을 시도해야 하는가?

질문 2. MinMax 스케일링을 진행한 데이터셋 중 ( 0 아니면 1에 매우 가깝거나 그냥 0, 1인 데이터) 노이즈와 같이 생각하고 제거 혹은 Imputation을 다시 진행해야 하는가?

**Comment by kang961105** [comment]
1. Normalize를 정규화라는 의미로 알고 있는데 MInMax가 데이터들을 0~1사이로 정규화 하는걸로 알고 있습니다. 추가적으로 Normalize 한다는 말이 무슨말인지 이해가 가지 않네요.

2. 이상치를 보정하고 난 뒤 스케일링을 진행한 데이터셋에서는 노이즈라고 생각되는 값이 거의 없을거라고 봅니다. 오히려 이상치 제거가 되지 않았다면 MinMax를 통한 결과가 이상하게 나올꺼에요. 결론적으로는 스케일링 전에 이상치 제거를 확실히 했다면 스케일링이 된 데이터에는 따로 노이즈라고 불릴 값이 없다고 생각해요.

**Comment by ChoiJunhee** [comment]
> 1. Normalize를 정규화라는 의미로 알고 있는데 MInMax가 데이터들을 0~1사이로 정규화 하는걸로 알고 있습니다. 추가적으로 Normalize 한다는 말이 무슨말인지 이
해가 가지 않네요.

답변 : scikit learn에 skllearn.preprocessing에 Nomalizer 라는 기능이 있는데,  MINMAX와는 조금 다른 방식으로 작동합니다. 업로드 되지는 않았지만 여러번 결과물을 가지고 확인한 결과 기존 두 방식이 더 낫다는 판단을 내리게 되었습니다.
-> Normalize가 row마다 정규화 되는 점을 transpose를 사용해서 이용하였습니다.


> 2. 이상치를 보정하고 난 뒤 스케일링을 진행한 데이터셋에서는 노이즈라고 생각되는 값이 거의 없을거라고 봅니다. 오히려 이상치 제거가 되지 않았다면 MinMax를 통한 결과가 이상하게 나올꺼에요. 결론적으로는 스케일링 전에 이상치 제거를 확실히 했다면 스케일링이 된 데이터에는 따로 노이즈라고 불릴 값이 없다고 생각해요.


답변 : MINMAX 알고리즘을 사용하여 정규화한 파일을 확인해 보시면 일부 피쳐가 0 과 1, 아니면 매우 근접하게 구성되어 있습니다. 진짜 0밖에 없는 그런 피쳐도 있습니다...  (STD 알고리즘에서는 없습니다.) 


계획에 대한 추가 의견 주시면 반영하여 버전업 하겠습니다.

**Comment by kang961105** [comment]
2. 코드

> > 1. Normalize를 정규화라는 의미로 알고 있는데 MInMax가 데이터들을 0~1사이로 정규화 하는걸로 알고 있습니다. 추가적으로 Normalize 한다는 말이 무슨말인지 이
> >    해가 가지 않네요.
> 
> 답변 : scikit learn에 skllearn.preprocessing에 Nomalizer 라는 기능이 있는데, MINMAX와는 조금 다른 방식으로 작동합니다. 업로드 되지는 않았지만 여러번 결과물을 가지고 확인한 결과 기존 두 방식이 더 낫다는 판단을 내리게 되었습니다.
> -> Normalize가 row마다 정규화 되는 점을 transpose를 사용해서 이용하였습니다.
> 
> > 1. 이상치를 보정하고 난 뒤 스케일링을 진행한 데이터셋에서는 노이즈라고 생각되는 값이 거의 없을거라고 봅니다. 오히려 이상치 제거가 되지 않았다면 MinMax를 통한 결과가 이상하게 나올꺼에요. 결론적으로는 스케일링 전에 이상치 제거를 확실히 했다면 스케일링이 된 데이터에는 따로 노이즈라고 불릴 값이 없다고 생각해요.
> 
> 답변 : MINMAX 알고리즘을 사용하여 스케일링한 파일을 확인해 보시면 일부 피쳐가 0 과 1, 아니면 매우 근접하게 구성되어 있습니다. 진짜 0밖에 없는 그런 피쳐도 있습니다... (STD 알고리즘에서는 없습니다.)
> 
> 계획에 대한 추가 의견 주시면 반영하여 버전업 하겠습니다.

**Comment by kang961105** [comment]
2.코드 읽어보니까 s4_all를 사용해서 MINMAX_all.csv를 만드셨는데 s4_all가 이상치 처리가 안된 데이터 같더라구요. minmax가 데이터를 0~1로 스케일링하는건데 이상치 처리가 되지않아서 일부피처의 값이 0과 1에 매우근접하게 있는거라고 생각이 되네요.

**Comment by ChoiJunhee** [comment]
> 2.코드 읽어보니까 s4_all를 사용해서 MINMAX_all.csv를 만드셨는데 s4_all가 이상치 처리가 안된 데이터 같더라구요. minmax가 데이터를 0~1로 스케일링하는건데 이상치 처리가 되지않아서 일부피처의 값이 0과 1에 매우근접하게 있는거라고 생각이 되네요.
> 
> 
> 
> 

아 이상치 처리 기준을 바꿨는데 그 때 반영이 안된 것 같네요 오늘 병원 가기전에 max iter 30으로 연산 다시해서 올리겠습니다

**Comment by ChoiJunhee** [comment]
@kang961105 0.1.8버전에서 SECOM 원 데이터 확인 결과

F209 피쳐는 0으로만 세팅되어 있었습니다...

결측치 처리, 이상치 처리로 걸러지지 않는 것은 당연한데

왜 표준편차 처리에서 걸러지지 않았는지 궁금하네요... 

이번 0.1.8 업데이트에서는 첫 번째 표준편차 필터링에서 기준을 조금 더 높여서 적용해 보도록 하겠습니다.


그리고 Feature Selection 관련 여러가지 방법론 들을 보고 있는데

기존에 사용했던 Wrapper Method 중 하나인 RFE를 포함하여

Embedded Method를 추가로 사용해 볼 계획입니다.
