### ISSUE TITLE
히스토그램

### ISSUE THREAD

**Issue by zhanghuiyan99** [ChoiJunhee/INE5015_bigdata_analytics#29]
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
a = np.random.randn(100)
s = pd.Series(a) 
plt.hist(s)
plt.show()
sns.distplot(fail)
plt.show()
sns.distplot(pass)
plt.show()

data=np.random.normal(size=(10,4)) 
lables = ['pass','fail']
plt.boxplot(data,labels=lables)
plt.show()
df = pd.DataFrame(data, columns=lables)
sns.boxplot(data=df)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
uci-secom.csv_long = sns.load_dataset("uci-secom.csv")
uci-secom.csv = uci-secom.csv_long.pivot(’fail’,’pass’)
f, ax = plt.subplots(figsize=(9, 6))
sns.heatmap(uci-secom.csv)

**Comment by ChoiJunhee** [comment]
good 

but you must had to visualize step folder's csv files......
😭

**Comment by ChoiJunhee** [comment]
> good
> 
> but you must had to visualize step folder's csv files......
> 😭

Implement it through the csv file in the step of 0.1.8 version, and capture the image and upload it. @zhanghuiyan99

**Comment by ChoiJunhee** [comment]
> > good
> > but you must had to visualize step folder's csv files......
> > 😭
> 
> Implement it through the csv file in the step of 0.1.8 version, and capture the image and upload it. @zhanghuiyan99

use it 0.2.0 pre-release version
