### ISSUE TITLE
리팩토링 과정 도움 요청 

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#3]
#2 이슈에 대해 도움을 요청합니다. 

해당 파일은 ipnyb 폴더에 Refine 이라는 이름으로 들어있습니다.

제가 질문을 적어둔 주석이 2개인가 3개인가 되는데 

그 부분에 대해 답변 해주시면 감사하겠습니다.

**Comment by ChoiJunhee** [comment]
![image](https://user-images.githubusercontent.com/43108674/118775112-89800700-b8c1-11eb-8d13-ab92be70c110.png)

여기서 Feature중 V7을 사용한 이유와, 가중치는 어떤 기준으로 하셨는지 궁금합니다.

**Comment by kang961105** [comment]
가중치는 보통 1.5정도를 주는데 조금 더 분산을 주고 싶어서 2로 설정했어요

**Comment by ChoiJunhee** [comment]
> 가중치는 보통 1.5정도를 주는데 조금 더 분산을 주고 싶어서 2로 설정했어요

넵 감사합니다.

아마 오늘 8시 전까지 완성본 올릴 수 있을 것 같아요.
