### ISSUE TITLE
Pre-Released 0.2.0 버전 관련 요청 

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#30]
커밋 메시지에도 남기긴 했으나 이슈로도 한번 더 공지합니다.

https://github.com/ChoiJunhee/INE5015_bigdata_analytics/commit/27a55fad68705f3a7c106ceae490f3c764ca4ae1

---

두 가지 Feature Selection 방법을 사용하였고,

KBest 방식의 데이터 프레임은 열 이름이 날아가서 새로 인덱스 번호가 부여된 것입니다. 
고쳐야 하는데 조금 헷갈리는 부분이 있어 아직 회사라서... 퇴근하고 나면... 오늘 내로는 어려울 것 같습니다.
(Feature 번호랑 혼동하시면 안됩니다. 시각화 혹은 피쳐를 확인하실 때 유의하시길 바랍니다.)

#12 
**step 6, 7에 대한 CSV 파일들을 확인하신 후, 각 방법을 비교할 수 있는 시각화 이미지 데이터를 요청합니다.**

**월요일까지 최종 보고서, 발표자료를 제출해야 하는데 최소한 금요일 21:00, 늦어도 금요일 자정까지는 보내주셔야 합니다.**

**시각화 부분에 어려움이 있는 팀원들을 위해 이번에 요청하는 데이터의 퀄리티는 고려하지 않겠습니다.**

---

추가 업데이트 예정은 0.2.1 버전에서 Oversampling 결과와 DownSampling 결과를 비교할 예정이고

0.2.2 에서 최종 발표에 적합한 부분을 제외하고 주석 처리해 제출할 예정입니다.

**Comment by kang961105** [comment]
1.  step1) 데이터가 반이상이 날아가는데 std < 1 로 하는 이유가 뭔지 (592개에서 247개가 됨)

2.  전처리 과정에서 어떤게 성능이 좋았는지 판단을 어떤기준으로 했는지 (시각화 데이터를 확인해서 했나요?)

3.  outlier_processing함수에서 아웃라이어가 percent보다 많은 비율을 가진 피처를 제거하는거 같은데 percent보다 작은 비율의 아웃라이어의 값을 가진 피처는 제거를 왜 안하는지.

4.  step5) 아웃라이어 제거를 한 뒤 std를 맨처음에 처리했는데 왜 또 std<0.5제거를 사용 했는지

5.  FeatureSelection부분에서  SelectKBest와 RFE를 어떤식으로 적용했는지 코드로 봐서는 잘 이해가 안가는데 설명해주실수 있을까요.

6. 시각화 내일 점심에 해서 보내드릴께요

**Comment by ChoiJunhee** [comment]
> 1. step1) 데이터가 반이상이 날아가는데 std < 1 로 하는 이유가 뭔지 (592개에서 247개가 됨)

이는 0.1 버전대에 이미지가 있습니다. 
0.1.1 버전의 step4 폴더에 있는 pass/fail간 IQR 데이터
0.1.4 버전에 각 폴더 별로 참고용 이미지가 있습니다.  (Step2, Step3, Step4, Step5)
(visualization image / r3 / 에는 표준편차/pass/fail간 데이터를 확인할 수 있습니다.)

일부 저장되지 않은 데이터가 있으나 결과적으로 Step 0, 표준편차 간 데이터와 raw file을 확인해 보시면 표준편차가 극도로 큰 데이터가 있고, 0에 수렴하는 데이터도 있어 STD정규화에 영향을 줄 수 있는 요인을 제거하는 방향으로 진행했습니다.

여기서 표준편차가 큰 피쳐는 왜 제거하지 않았냐는 질문이 있을 수 있는데, 이는 이상치 제거에서 이상치가 제거 된 후에 확인할 단계라 생각했습니다.

각 버전 별 csv 파일이 이름은 같아도 내용이 조금씩 다릅니다. 여기서 모델 학습에 있어 확실한 피쳐를 선별하기 위해서는 표준편차 1.0 이라 생각해 진행했습니다. ( 수치를 0.5로 조정하시고 데이터 파일을 다른 이름으로 저장 후 시각화 하여 보시면 이해가 빠를 듯 합니다)




> 2. 전처리 과정에서 어떤게 성능이 좋았는지 판단을 어떤기준으로 했는지 (시각화 데이터를 확인해서 했나요?)

위 답변으로 답변 일부를 대체하나, 어떤게 성능이 좋았다고는 할 수는 없습니다. 아직 모델링이 진행되지 않았기 때문에 확답은 어렵습니다.

판단에 따른 기준은 위와 동일하며, Fail 데이터 판별이라는 궁극적인 목적에 맞추어 일부 수치들을 여러번 조정하였습니다.


> 3. outlier_processing함수에서 아웃라이어가 percent보다 많은 비율을 가진 피처를 제거하는거 같은데 percent보다 작은 비율의 아웃라이어의 값을 가진 피처는 제거를 왜 안하는지.

..? Imputation 을 하기 때문이겠죠..? (max-iter는 기본값이 10이지만, max-iter 30으로 두고 진행했습니다.)



> 4. step5) 아웃라이어 제거를 한 뒤 std를 맨처음에 처리했는데 왜 또 std<0.5제거를 사용 했는지

아웃라이어가 제거되면 편차는 바뀌기 마련입니다. 교수님이 피드백 시간에 하셨던 말씀처럼 의미가 없는 피쳐를 제거하는 데 있어 도움이 되기 때문에 제거를 한 것입니다.
(이는 0.2.1 ~ 0.2.2 버전에서 더 많이 사용될 것 같습니다)


> 5. FeatureSelection부분에서  SelectKBest와 RFE를 어떤식으로 적용했는지 코드로 봐서는 잘 이해가 안가는데 설명해주실수 있을까요.


selectKBest는 Feature Selection 중에서 단일 변수를 선택하는 방식입니다.
각각의 독립변수 (Feature)를 하나씩 사용하여 예측모형의 성능을 판단한 뒤, Classification 성능에 도움이 되는 변수들만 선택하는 방식으로, 0.2 프리 릴리즈에서는 약 25%를 제거하도록 하였습니다.
단, 피쳐 각각의 성능이 좋다고 해서 전체 성능이 좋아지지는 않습니다. 시각화 자료가 부족하여 제약 조건이나 다른 기능을 추가하지는 않았습니다.

RFE는 아시겠지만 위 SelectKBest 와는 약간 대치되는 성향이 있습니다. 전체 피쳐들을 가지고 필요성이 떨어지는 피쳐들을 하나하나 제거하는 방식입니다. 여기서 RFECV를 사용하면 Cross Validation 으로 피쳐들의 수 까지 조절할 수 있지만, 수업 시간에 교수님이 말씀하셨던 k-fold를 진행하기엔 Fail 데이터가 부족하기 때문에 RFECV는 사용하지 않았습니다. 



> 6. 시각화 내일 점심에 해서 보내드릴께요

네 감사합니다. 

보고서 초안을 제가 주말에 완성하면 PPT 초안을 만들어 주신 뒤에

완성도를 높히기 위해 서로 보고서와 PPT를 인스펙션하고 

각자 만든 다시 보고서와 피피티를 수정해서 교환하는  방식으로 

발표 자료와 최종 보고서를 만들고 싶은데 주말에 시간 되는지 카톡으로 알려주시길 바랍니다...

**Comment by ChoiJunhee** [comment]
파일 확인 및 사후조치 (0.2.0 hotfix) 하였음. 
hotfix로 확인된 버그는 금일 해결 예정
