### ISSUE TITLE
월요일 마감을 위한 회의

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#31]
@HwangTr 

@zhanghuiyan99 

Everyone doesn't have much time due to the exam schedule, so I would like to ask for your help, even today.

The above has been notified several times through KakaoTalk, e-mail, and git issues.

**Please check the KakaoTalk group chat room.**

**Comment by zhanghuiyan99** [comment]
요 며칠 일이 좀 많아서 소식을 못 봤어요.죄송합니다.내가 지금 가서 확인할게요.
