### ISSUE TITLE
[토의] 모델링 작업 분배 및 진행 계획 

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#5]
[데이터 처리]

< 데이터 전처리 >

1. 데이터 분석 
2. 데이터 가공
3. 데이터 보정

[시각화 과정]

< 데이터 시각화 >
전처리가 이루어진 데이터들을 직관적으로 알 수 있도록 
데이터와 그 과정, 관계 등을 시각화 해야 합니다.

[ 모델링 과정 ]

< 모델 개발 >
다양한 관점을 갖되, 검증된 이론을 토대로
여러가지 모델을 시도, 개발

< 모델 튜닝 >
모델 개발의 연장선

< 모델 검증 >
여러 테스트셋을 통해 모델의 성능을 향상

총 3가지의 과정으로 나누어 보았습니다.

우선 데이터 전처리에서는 수업중에 배웠던 내용, 기존에 사용한 전처리 방법 등을 활용합니다.

모델링 과정에서는 '다양한 시도'를 하여 가장 성능이 좋은 모델을 구현하면 됩니다.

데이터 시각화 과정에서는 위에 나와있듯 개발 과정에 있어 필요한 부분의 시각화 자료를 만드시면 됩니다.
(plt, seaborn 등을 활용합니다.)

인원 분배 

데이터 전처리  :  1.5명
모델링 과정 : 1.5명
데이터 시각화 : 1명

저는 전처리와 모델링 과정에 있어 전반적인 기여를 하려 합니다.

각자 원하는 과정을 오늘 내로 댓글 남겨주시면 감사하겠습니다.

(읽어보면 좋은 글)
https://doorbw.tistory.com/229
https://brunch.co.kr/@data/10

**Comment by kang961105** [comment]
저는 모델링 부분 중점으로 할께요. 제 생각에는 전처리하면서 시각화를 통해 전처리 성능을 알아가는거라고 생각하는데 전처리랑 시각화랑 묶어서 2~3명으로 하는게 좋지 않을까요?
모델링은 저 혼자해도 괜찮아요

**Comment by ChoiJunhee** [comment]
@kang961105 

데이터 시각화를 따로 빼 둔 이유는... 개발을 하는 과정에서는 간략히 우리끼리 알 정도로만 구현해두고
이제 발표나 토론 등등 데이터 모델링에 대한 시각적 요소가 필요할 자료를 전반적으로 제작 하는 것으로 생각하고 있습니다.

모델링이나 전처리 과정에서 여러 시각을 통해 다양한 결과물을 도출하고 선별하는 과정을 거치면 더 좋은 결과물이 나올 것 같아서 저렇게 구성했습니다.

**Comment by ChoiJunhee** [comment]
@HwangTr @zhanghuiyan99 데이터 전처리 / 데이터 시각화 중 중점적으로 맡고 싶은 파트를 알려주세요.

**Comment by ChoiJunhee** [comment]
> 저는 모델링 부분 중점으로 할께요. 제 생각에는 전처리하면서 시각화를 통해 전처리 성능을 알아가는거라고 생각하는데 전처리랑 시각화랑 묶어서 2~3명으로 하는게 좋지 않을까요?
> 모델링은 저 혼자해도 괜찮아요

음 괜찮으시면, 전처리 방법이 어느정도 가닥이 잡히기 전까지 모델링 관련한 정보를 수집, 요약 해주시고 폴더에 올려주시면 
제가 조사한 부분과 취합한 뒤 모델링에 대한 방법을 논의해 보는것으로 하려고 합니다. @kang961105 

다른 분들도 답변을 빨리 해주셔야 하는데... ㅠㅠㅠ

**Comment by HwangTr** [comment]
제가 데이터 시각화 쪽 맡는 게 나을 것 같아요.

**Comment by ChoiJunhee** [comment]
> 제가 데이터 시각화 쪽 맡는 게 나을 것 같아요.

알겠습니다. 데이터 시각화의 중요 포인트는 발표할 때 있어 보이게.... 하면 더 좋겠지만

데이터 구조에 대한 직관성을 기조로 두고 작업하시면 됩니다.

+ 기존에 @kang961105 님이 만든 모델링 예제가 있으니 해당 파일을 참고하시어 더 나은 결과를 낼 수 있도록 다같이 노력합시다

**Comment by ChoiJunhee** [comment]
대강 주력해야 할 파트를 정했으니 이번 이슈는 닫겠습니다.
