### ISSUE TITLE
Request to submit data compared to other groups

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#6]
토론2-6조의  조리가 정확합니다.
토론1-3조 해명 데이터가 분명합니다.

_Originally posted by @zhanghuiyan99 in https://github.com/ChoiJunhee/INE5015_bigdata_analytics/issues/1#issuecomment-844878600_

#1 이슈에서 분리하였습니다. (Originally, this should be done by @zhanghuiyan99 )

**Comment by ChoiJunhee** [comment]
Amendment request @zhanghuiyan99 

If you haven't prepared any informations, can you upload another group?

Originally, I was supposed to do group A (Discussion 1: Group 3, Discussion 2: Group 6). (Some materials are produced)

please respond this comment...

**Comment by zhanghuiyan99** [comment]
D (토론 1 - 6조, 토론 2 - 5조)
그럼 제가 이걸 할게요.

**Comment by ChoiJunhee** [comment]
> D (토론 1 - 6조, 토론 2 - 5조)
> 그럼 제가 이걸 할게요.

Okay. Please briefly summarize the strengths of the other groups data and the degree of difference from our data.
