### ISSUE TITLE
데이터 전처리 과정 _ 메인 이슈

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#7]
데이터 전처리 과정은 #5 이슈에서 아래와 같이 크게 3가지로 나누었습니다.

이번 이슈에서는 assignees 분들이 해주셔야 하는 일을 간략하게 적어 보았습니다.
(하나의 예시 라고 생각하시고, Reference를 참고하여 자유롭게 데이터를 가공해 주세요.

[빅데이터 분석기사 Reference](https://velog.io/@dayday/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%B6%84%EC%84%9D%EA%B8%B0%EC%82%AC-%EB%8C%80%EB%B9%84-%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%AA%A8%EB%8D%B8%EB%A7%811-%EB%B6%84%EC%84%9D-%EB%AA%A8%ED%98%95-%EC%84%A4%EA%B3%84)
[EDA에 대한 Reference](https://eda-ai-lab.tistory.com/13)

---
### 데이터 전처리 **(due : 2021/05/23)**

_요청에 따라 기한을 연장했습니다... 한번 더....._

---

**1. 데이터 분석**
- Raw-data 에 해당하는 SECOM 파일을 그래프나, 통계적 수치를 통해 직관적인 이해
- 직접적인 데이터 확인을 통해 Feature의 개별적인 속성을 확인합니다.
- 여기서 데이터 시각화 과정은 매우 중요합니다. Feature의 특성, 상관관계, 패턴 등을 명확히 알 수 있어야 합니다.
- 데이터에 대한 전반적인 이해가 되었고, 목표를 이루었다 판단되면 2단계를 진행합니다.

_-Intuitive understanding of SECOM files corresponding to raw-data through graphs or statistical figures
-Understand the individual properties of the feature
-The data visualization process is very important here. Characteristics, correlations, patterns, etc. must be clearly visible.
-If you have a general understanding of the data and you are determined to have achieved your goal, proceed to step 2._

---

**2. 데이터 가공**
- 개별적인 데이터 관찰도 중요하지만, 시간상 여유가 없어 적절한 요약 통계 지표를 만들어 봅니다. (이 때도 데이터 시각화 과정을 거친다면, 더 직관적인 이해가 되겠죠?)
- 결측치와 이상치를 정의해야 합니다. 현재 올라온 모델링 구조에서는 결측치와 이상치를 정의하고, 보정하는 과정에서 주관이 과다 포함되어, 근거가 부족한 상황입니다. 이를 참고하여 우리가 얻어야 하는 데이터 셋이 무엇인지, 어떻게 데이터를 가공할 것인지를 생각하고 구현하시길 바랍니다.

_-Observation of individual data is also important, but there is not enough time to make an appropriate summary statistical index. (If you go through the data visualization process at this time, it will make a more intuitive understanding, right?)

-Missing and outliers must be defined. In the currently uploaded modeling structure, there is insufficient evidence because subjectivity is excessive in the process of defining and correcting missing values and outliers.

Please refer to this to think and implement what data set we need to obtain and how to process the data._

---

**3. 데이터 보정**
- 위 과정에서 결측치, 이상치 등 없애도 되는 Feature는 없애고, 필요한 Feature는 여러가지 방법 (oversampling 등등)을 통해 데이터 셋을 완성 시킵니다.

- 해당 과정에서는 통계적 기법, 트리 기반 기법, 최적화 기법, GAN 기법 등을 사용하면 됩니다.

_-In the above process, features that can be eliminated such as missing values and outliers are removed, and necessary features are completed through various methods (oversampling, etc.) to complete the data set._

_-In this course, you can use statistical techniques, tree-based techniques, optimization techniques, and GAN techniques._

---

@ChoiJunhee  @zhanghuiyan99 @kang961105 
위 3명은 각각 제한 기간 안에 데이터 전처리 과정을 레포트로 남겨주시거나, 주피터 노트북 파일, 파이썬 파일 등으로 서로 확인할 수 있도록 자료를 업로드 해주시길 바랍니다. 
데이터 시각화 파일 (대강 테스트용 말고...) 요청은 새 issue를 만들어 assignees에 @HwangTr 을 추가하여 요청할 수 있습니다.

_Please upload the data so that you can check the data preprocessing process in a report file, Jupiter notebook file, Python file, etc. within the limited period._

_Requests_ for data visualization files (not roughly for testing...) can be requested by creating a new issue and adding @HwangTr to _assignees._

@HwangTr 
데이터 분석과 데이터 가공 과정에서 중요한 부분을 시각화 하여 자료를 만들어 주시길 바랍니다. 전처리 과정 중에 요청 할 것같은 부분을 예상해 미리 자료를 준비해 주셔도 좋고, 분석과 가공, 보정처리 도중에 올라오는 issue 를 통해 자료를 제공하셔도 좋습니다.

---

궁금한 사항이 있으면 언제든 댓글을 남겨주시길 바랍니다.

개인적으로는 데이터 전처리 파일을 .py 으로 업로드 해주셨으면 좋겠습니다.
수시로 commit 을 해두다 보면 서로 서로 얻어 가는 것들이 많겠죠?

**Comment by ChoiJunhee** [comment]
모든 과정에는 근거가 필요합니다. 
구글링을 통해 최소한의 근거를 APA 스타일로 첨부하십시오.

_Every process needs evidence.
Attach minimal evidence in APA style via google._


( 논문 검색 하기 좋은 사이트 )
https://scholar.google.co.kr/schhp
https://information.hanyang.ac.kr

**Comment by ChoiJunhee** [comment]
@HwangTr 이미지 시각화 관련 카톡 확인해주세요.

https://wikidocs.net/92071

**Comment by zhanghuiyan99** [comment]
[Iliou_et_al_AIAB_2015.pdf](https://github.com/ChoiJunhee/INE5015_bigdata_analytics/files/6529846/Iliou_et_al_AIAB_2015.pdf)

https://towardsdatascience.com/data-pre-processing-techniques-you-should-know-8954662716d6

various algorithms and methods used in data preprocessing

**Comment by ChoiJunhee** [comment]
https://github.com/ChoiJunhee/INE5015_bigdata_analytics/blob/19c978032a0a4b5ae6a739c56317572a01441ae4/Documents/Report/Data_preprocessing_%EC%B5%9C%EC%A4%80%ED%9D%AC.pdf

**Comment by ChoiJunhee** [comment]
앙상블 기법 관련 내용 모음 (학습용) 

https://bkshin.tistory.com/entry/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-11-%EC%95%99%EC%83%81%EB%B8%94-%ED%95%99%EC%8A%B5-Ensemble-Learning-%EB%B0%B0%EA%B9%85Bagging%EA%B3%BC-%EB%B6%80%EC%8A%A4%ED%8C%85Boosting

https://data-matzip.tistory.com/entry/%EC%95%99%EC%83%81%EB%B8%94-%EA%B8%B0%EB%B2%95-%EC%A0%95%EB%A6%AC-1-%EC%95%99%EC%83%81%EB%B8%94Ensemble-%EA%B8%B0%EB%B2%95%EA%B3%BC-%EB%B0%B0%EA%B9%85Bagging-%EB%B6%80%EC%8A%A4%ED%8C%85Boosting-%EC%8A%A4%ED%85%8C%EC%9D%B4%ED%82%B9Stacking

https://assaeunji.github.io/ml/2020-08-06-tree/
