### ISSUE TITLE
비대면 토의 일정

### ISSUE THREAD

**Issue by ChoiJunhee** [ChoiJunhee/INE5015_bigdata_analytics#9]
현재 진행중인 프로젝트에 대해 의견을 나누고자 합니다.

05/23일 부터 05/24일 사이에 각자 '불가능한 시간' 을 적어주세요.

취합 후 시간 공지하도록 하겠습니다.

(이 내용은 카카오톡 공지로 올라갈 예정입니다.)

**Comment by HwangTr** [comment]
월요일 오전만 어려울 것 같아요

**Comment by ChoiJunhee** [comment]
@zhanghuiyan99 @kang961105

**Comment by ChoiJunhee** [comment]
카카오톡으로 일정 조정했습니다.
